server:
  port: ${SERVER_PORT:8090}
spring:
  application:
    name: "projectPragma"
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      initial-size: ${DB_POOL_INITIAL_SIZE:10}
      max-size: ${DB_POOL_MAX_SIZE:20}
      max-idle-time: ${DB_POOL_IDLE_TIME:30m}
      validation-query: SELECT 1
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.xml
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
adapters:
  r2dbc:
    host: ${DB_HOST}
    port: ${DB_PORT}
    database: ${DB_NAME}
    schema: ${DB_SCHEMA:public}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus,metrics"
  endpoint:
    health:
      probes:
        enabled: true
    metrics:
      enabled: true
springdoc:
  api-docs:
    enabled: false  # Disable in production
  swagger-ui:
    enabled: false  # Disable in production
cors:
  allowed-origins: "${CORS_ALLOWED_ORIGINS}"
logging:
  level:
    root: ${LOG_LEVEL:WARN}
    co.com.bancolombia: ${LOG_LEVEL_APP:INFO}
  file:
    name: ${LOG_FILE_PATH:/var/logs/pragma.log}
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION:1800000}  # 30 minutes in prod