server:
  port: 8080
spring:
  application:
    name: "projectPragma"
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/project_pragma
    username: postgres
    password: 123456
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
      validation-query: SELECT 1
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/project_pragma
    user: postgres
    password: 123456
adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: project_pragma
    schema: public
    username: postgres
    password: 123456
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs                                                                          
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: false
  packages-to-scan: co.com.bancolombia.api
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
logging:
  level:
    root: INFO
  file:
    name: logs/crediya.log